// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "github.com/justalternate/fleettui/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockMetricsCollector is an autogenerated mock type for the MetricsCollector type
type MockMetricsCollector struct {
	mock.Mock
}

type MockMetricsCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsCollector) EXPECT() *MockMetricsCollector_Expecter {
	return &MockMetricsCollector_Expecter{mock: &_m.Mock}
}

// CollectMetrics provides a mock function with given fields: ctx, node, config
func (_m *MockMetricsCollector) CollectMetrics(ctx context.Context, node *domain.Node, config *domain.Config) (*domain.Metrics, error) {
	ret := _m.Called(ctx, node, config)

	if len(ret) == 0 {
		panic("no return value specified for CollectMetrics")
	}

	var r0 *domain.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Node, *domain.Config) (*domain.Metrics, error)); ok {
		return rf(ctx, node, config)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Node, *domain.Config) *domain.Metrics); ok {
		r0 = rf(ctx, node, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Node, *domain.Config) error); ok {
		r1 = rf(ctx, node, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsCollector_CollectMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectMetrics'
type MockMetricsCollector_CollectMetrics_Call struct {
	*mock.Call
}

// CollectMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - node *domain.Node
//   - config *domain.Config
func (_e *MockMetricsCollector_Expecter) CollectMetrics(ctx interface{}, node interface{}, config interface{}) *MockMetricsCollector_CollectMetrics_Call {
	return &MockMetricsCollector_CollectMetrics_Call{Call: _e.mock.On("CollectMetrics", ctx, node, config)}
}

func (_c *MockMetricsCollector_CollectMetrics_Call) Run(run func(ctx context.Context, node *domain.Node, config *domain.Config)) *MockMetricsCollector_CollectMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Node), args[2].(*domain.Config))
	})
	return _c
}

func (_c *MockMetricsCollector_CollectMetrics_Call) Return(_a0 *domain.Metrics, _a1 error) *MockMetricsCollector_CollectMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsCollector_CollectMetrics_Call) RunAndReturn(run func(context.Context, *domain.Node, *domain.Config) (*domain.Metrics, error)) *MockMetricsCollector_CollectMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsCollector creates a new instance of MockMetricsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsCollector {
	mock := &MockMetricsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
