// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "github.com/justalternate/fleetui/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockSSHClient is an autogenerated mock type for the SSHClient type
type MockSSHClient struct {
	mock.Mock
}

type MockSSHClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSHClient) EXPECT() *MockSSHClient_Expecter {
	return &MockSSHClient_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: ctx, node
func (_m *MockSSHClient) Connect(ctx context.Context, node *domain.Node) error {
	ret := _m.Called(ctx, node)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Node) error); ok {
		r0 = rf(ctx, node)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSSHClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockSSHClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - node *domain.Node
func (_e *MockSSHClient_Expecter) Connect(ctx interface{}, node interface{}) *MockSSHClient_Connect_Call {
	return &MockSSHClient_Connect_Call{Call: _e.mock.On("Connect", ctx, node)}
}

func (_c *MockSSHClient_Connect_Call) Run(run func(ctx context.Context, node *domain.Node)) *MockSSHClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Node))
	})
	return _c
}

func (_c *MockSSHClient_Connect_Call) Return(_a0 error) *MockSSHClient_Connect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSSHClient_Connect_Call) RunAndReturn(run func(context.Context, *domain.Node) error) *MockSSHClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with no fields
func (_m *MockSSHClient) Disconnect() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSSHClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockSSHClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *MockSSHClient_Expecter) Disconnect() *MockSSHClient_Disconnect_Call {
	return &MockSSHClient_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *MockSSHClient_Disconnect_Call) Run(run func()) *MockSSHClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSSHClient_Disconnect_Call) Return(_a0 error) *MockSSHClient_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSSHClient_Disconnect_Call) RunAndReturn(run func() error) *MockSSHClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteCommand provides a mock function with given fields: ctx, command
func (_m *MockSSHClient) ExecuteCommand(ctx context.Context, command string) (string, error) {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteCommand")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, command)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSSHClient_ExecuteCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteCommand'
type MockSSHClient_ExecuteCommand_Call struct {
	*mock.Call
}

// ExecuteCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - command string
func (_e *MockSSHClient_Expecter) ExecuteCommand(ctx interface{}, command interface{}) *MockSSHClient_ExecuteCommand_Call {
	return &MockSSHClient_ExecuteCommand_Call{Call: _e.mock.On("ExecuteCommand", ctx, command)}
}

func (_c *MockSSHClient_ExecuteCommand_Call) Run(run func(ctx context.Context, command string)) *MockSSHClient_ExecuteCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSSHClient_ExecuteCommand_Call) Return(_a0 string, _a1 error) *MockSSHClient_ExecuteCommand_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSSHClient_ExecuteCommand_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockSSHClient_ExecuteCommand_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function with no fields
func (_m *MockSSHClient) IsConnected() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSSHClient_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockSSHClient_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockSSHClient_Expecter) IsConnected() *MockSSHClient_IsConnected_Call {
	return &MockSSHClient_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockSSHClient_IsConnected_Call) Run(run func()) *MockSSHClient_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSSHClient_IsConnected_Call) Return(_a0 bool) *MockSSHClient_IsConnected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSSHClient_IsConnected_Call) RunAndReturn(run func() bool) *MockSSHClient_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSSHClient creates a new instance of MockSSHClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSHClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSHClient {
	mock := &MockSSHClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
