// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/justalternate/fleettui/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockConfigLoader is an autogenerated mock type for the ConfigLoader type
type MockConfigLoader struct {
	mock.Mock
}

type MockConfigLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigLoader) EXPECT() *MockConfigLoader_Expecter {
	return &MockConfigLoader_Expecter{mock: &_m.Mock}
}

// LoadConfig provides a mock function with given fields: path
func (_m *MockConfigLoader) LoadConfig(path string) (*domain.Config, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Config, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Config); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigLoader_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type MockConfigLoader_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
//   - path string
func (_e *MockConfigLoader_Expecter) LoadConfig(path interface{}) *MockConfigLoader_LoadConfig_Call {
	return &MockConfigLoader_LoadConfig_Call{Call: _e.mock.On("LoadConfig", path)}
}

func (_c *MockConfigLoader_LoadConfig_Call) Run(run func(path string)) *MockConfigLoader_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigLoader_LoadConfig_Call) Return(_a0 *domain.Config, _a1 error) *MockConfigLoader_LoadConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigLoader_LoadConfig_Call) RunAndReturn(run func(string) (*domain.Config, error)) *MockConfigLoader_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// LoadHosts provides a mock function with given fields: path
func (_m *MockConfigLoader) LoadHosts(path string) (*domain.HostsConfig, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for LoadHosts")
	}

	var r0 *domain.HostsConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.HostsConfig, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.HostsConfig); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HostsConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigLoader_LoadHosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadHosts'
type MockConfigLoader_LoadHosts_Call struct {
	*mock.Call
}

// LoadHosts is a helper method to define mock.On call
//   - path string
func (_e *MockConfigLoader_Expecter) LoadHosts(path interface{}) *MockConfigLoader_LoadHosts_Call {
	return &MockConfigLoader_LoadHosts_Call{Call: _e.mock.On("LoadHosts", path)}
}

func (_c *MockConfigLoader_LoadHosts_Call) Run(run func(path string)) *MockConfigLoader_LoadHosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigLoader_LoadHosts_Call) Return(_a0 *domain.HostsConfig, _a1 error) *MockConfigLoader_LoadHosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigLoader_LoadHosts_Call) RunAndReturn(run func(string) (*domain.HostsConfig, error)) *MockConfigLoader_LoadHosts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigLoader creates a new instance of MockConfigLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigLoader {
	mock := &MockConfigLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
